apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jvaltz/cd-gitops
  newTag: 709dc9c06a4ad360baf0dfa7fbbbf12d9a14599d
