name: CDGitops

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          repository: ${{ secrets.DOCKER_USERNAME }}/cd-gitops
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cd-gitops:${{ github.sha }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_BRANCH=${{ github.ref }}
            GIT_URL=${{ github.event.repository.html_url }}
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VERSION=1.0.0
          context: .
          file: ./Dockerfile

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1.0.0
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image goserver=${{ secrets.DOCKER_USERNAME }}/cd-gitops:${{ github.sha }}

      - name: Commit
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -am "Bump new version"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: jaovaltz/gitopsfc
          branch: main